name: Build and Deploy Docs

on:
  push:
    branches: 
      - master
    paths-ignore:
      - '!docs/**'
      - '.github/**'

env:
  VERSION: '1.0.0-beta-6'
  BRANCH: "master"
  COMMIT: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false      
      - name: Update tokens in project files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["docs/*.md", "docs/**/*.md", "*.csproj", "**/*.csproj"]'
      - uses: nikeee/docfx-action@master
        name: Build Documentation
        with:
          args: docs/docfx.json
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_DOCS }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_site # The folder the action should deploy.
