name: Build and Deploy Docs

on:
  push:
    branches: 
      - master
    paths-ignore:
      - '!docs/**'
      - '.github/**'

env:
  VERSION: '1.0.0-beta-7'
  BRANCH: 'master'
  COMMIT: ''
  DOCFX_SOURCE_BRANCH_NAME: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - uses: dotnet/nbgv@master
        with:
          setAllVars: true
      - name: Setting VERSION and BRANCH env
        run: |
          echo "::set-env name=VERSION::$NBGV_NuGetPackageVersion"
          echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - name: Update tokens in project files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["docs/*.md", "docs/**/*.md", "*.csproj", "**/*.csproj"]'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.202'
      - name: Building library and docs
        run: |
          dotnet restore src
          dotnet build src/bunit.core/ --no-restore -p:version=$VERSION
          dotnet build src/bunit.web/ --no-restore -p:version=$VERSION
          dotnet build src/bunit.xunit/ --no-restore -p:version=$VERSION
          dotnet build docs/docs.csproj
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_DOCS }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_site # The folder the action should deploy.
          CLEAN: true
