name: Build and Deploy Docs

on:
  push:
    branches: 
      - master
    paths-ignore:
      - '!docs/**'
      - '.github/**'

env:
  VERSION: ''

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - uses: dotnet/nbgv@master
        with:
          setAllVars: true
      - name: Setting VERSION
        run: echo "::set-env name=VERSION::$NBGV_NuGetPackageVersion"
      - name: Update tokens in project files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["docs/*.md", "docs/**/*.md", "*.csproj", "**/*.csproj"]'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.202'
      - name: Building library and docs
        run: |
          dotnet restore src
          dotnet build src/bunit.core/ --no-restore -p:version=$VERSION
          dotnet build src/bunit.web/ --no-restore -p:version=$VERSION
          dotnet build src/bunit.xunit/ --no-restore -p:version=$VERSION
          dotnet build docs/
          dotnet build docs/
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}          
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/_site 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
