name: Build and Deploy Docs

on:
  push:
    branches: 
      - master
    paths-ignore:
    - 'docs/**'
    - '.github/**'

env:
  VERSION: '0.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Get current version
        id: currentVersion
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"  
      - name: Set version env
        run: echo "::set-env name=VERSION::${steps.currentVersion.outputs.tag\/v/}"      
      - name: Update tokens in project files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["*.md", "**/*.md"]'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.101'
      - name: Build docs
        run: dotnet build docs/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_site # The folder the action should deploy.
