name: CI

on: [push]

jobs:  
  build:    
    name: Executing tests
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'  
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - run: dotnet build -c Release -p:version=${{ steps.get_version.outputs.VERSION }} /nowarn:CS1591
    - run: dotnet test -c Release /nowarn:CS1591
