name: CD

on:
  push:
    tags: 
      - 'v*.*.*'

env:
  VERSION: 0.0.0
  BRANCH: "master"
  COMMIT: ''
  
jobs:  
  build:
    name: Build and verify library    
    runs-on: ubuntu-latest  
    steps:
      - name: Setting environment variables
        run: |          
          echo "::set-env name=COMMIT::$GITHUB_SHA"
          echo "::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}"                    
          echo Version $VERSION - Branch $BRANCH - Commit $COMMIT
      - run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
