name: CD

on:
  release:
    types:
      - published        
      - created
      - edited
      - prereleased

env:
  VERSION: 0.0.0
  BRANCH: "master"
  COMMIT: ""
  
jobs:  
  build:
    name: Build and verify library    
    runs-on: ubuntu-latest  
    steps:
      - name: Setting environment variables
        run: |          
          #echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
          echo "::set-env name=COMMIT::$GITHUB_SHA"
          echo "::set-env name=VERSION::${GITHUB_REF/refs\/tags\/v/}"      
      - run: echo Version $VERSION - Branch $BRANCH - Commit $COMMIT
