name: CD

on:
  push:
    tags: 
      - 'v*.*.*'

env:
  VERSION: 0.0.0
  BRANCH: ""
  COMMIT: ""
  
jobs:  
  build:
    name: Build and verify library    
    runs-on: ubuntu-latest  
    steps:
      - name: Setting environment variables
        run: |          
          echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
          echo "::set-env name=COMMIT::$GITHUB_SHA"
          echo "::set-env name=VERSION::${GITHUB_REF/refs\/tags\/v/}"                    
      - run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - run: echo Version $VERSION - Branch $BRANCH - Commit $COMMIT - release_version - $RELEASE_VERSION
